# see https://learnxinyminutes.com/docs/toml/ for syntax

# Note: the inverse mapping will be added automatically
[SPARQL_PREFIX_MAPPING]
    ":" =  "<irk:/builtins#>"
    "ct:" =  "<irk:/ocse/0.2/control_theory#>"
    "ack:" = "<irk:/ackrep#>"
    "ma:" = "<irk:/ocse/0.2/math#>"


[pyirkdjango]

# empty main_module -> load only builtins
main_module = ""
