# Note: this is not the real module for this URI it is an autogenerated subset for testing


import pyerk as p


__URI__ =  "erk:/ocse/0.2/agents"

keymanager = p.KeyManager(keyseed=1239)
p.register_mod(__URI__, keymanager)
p.start_mod(__URI__)

insert_entities = [
    func__create_person,
    I7435["human"],
    R7781["has family name"],
    R7782["has given name"],
    R3474["has ORCID"],
    R3475["has DBLP author ID"],
    I2746["Rudolf Kalman"],
    R1833["has employer"],
    I4853["Sophus Lie"],
    R6876["is named after"],
]

p.end_mod()
