# Note: this is not the real module for this URI it is an autogenerated subset for testing


import pyerk as p


__URI__ =  "erk:/ocse/0.2/agents"

keymanager = p.KeyManager(keyseed=1239)
p.register_mod(__URI__, keymanager)
p.start_mod(__URI__)

I2746 = create_person("Rudolf", "Kalman", "electrical engineer and mathematician")

R1833 = p.create_relation(
    R1__has_label="has employer",
    R2__has_description="specifies for which entity (organisation/person) the subject works",
    R33__has_corresponding_wikidata_entity="https://www.wikidata.org/entity/P108",
)


p.end_mod()
