"""Generic LLM-assisted authoring substrate for pyirk content modules.

This is the Claude-Code-native, lightweight variant of the MCP-based
authoring server sketched in ``docs/design/mcp_authoring.md``. Same value
props (retrieval-first; round-trip validation; structured append; explicit
modeling-fork escalation), simpler mechanics: a Python API plus a
subprocess call to ``claude -p``, instead of an MCP transport.

Source-specific extraction adapters (e.g. ``pyirk.authoring.lean``) sit on
top of this core. Adding a new source format means writing a new adapter,
not changing the core.
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Iterator, Optional, Tuple

from .. import core
from .. import irkloader

# ---------------------------------------------------------------------------
# Data classes


@dataclass
class EntityHit:
    """A retrieval result: an existing entity that could be reused or referenced."""

    short_key: str
    uri: str
    label: str
    description: str
    score: float = 0.0


@dataclass
class ProposalResult:
    """Result of an LLM proposal attempt."""

    kind: str  # "OK" or "FORK" or "ERROR"
    code: str = ""  # populated when kind == "OK"
    question: str = ""  # populated when kind == "FORK"
    options: list = field(default_factory=list)  # list[(letter, description)]
    raw: str = ""  # raw LLM response (for debugging / re-prompting)


@dataclass
class ClaudeCallResult:
    """Outcome of one ``claude -p`` invocation: response text plus usage metadata.

    ``cost_usd`` is the API-equivalent cost reported by the CLI
    (``total_cost_usd``); under subscription billing it is notional, but it is
    the right unit for usage accounting either way."""

    text: str
    cost_usd: Optional[float] = None
    duration_api_s: Optional[float] = None
    session_id: str = ""
    num_turns: Optional[int] = None


class ForkPending(Exception):
    """Raised by a non-interactive ``ask_user`` callback to signal that a FORK
    question cannot be answered in this run and the statement should be
    skipped (recorded as pending) instead of resolved arbitrarily."""

    def __init__(self, question: str, options: list):
        self.question = question
        self.options = options
        super().__init__(question)


# ---------------------------------------------------------------------------
# Session


@dataclass
class Session:
    """Holds the loaded pyirk state plus the working module path."""

    loaded_mods: dict = field(default_factory=dict)
    working_module_path: Optional[Path] = None
    working_module_prefix: str = ""

    def load_dependency(self, path: str, prefix: str):
        mod = irkloader.load_mod_from_path(path, prefix=prefix)
        self.loaded_mods[prefix] = mod
        return mod

    def all_entities(self) -> Iterator:
        for it in core.ds.items.values():
            yield it
        for r in core.ds.relations.values():
            yield r

    def dependency_label_index(self) -> str:
        """Flat label index of every entity defined in a loaded dependency.

        Helps the LLM reuse entities the lexical retrieval missed. Skips
        auto-generated scope artifacts (short keys with a lowercase second
        char like ``Ia12345`` / ``Ra...``) since they are scope-internal
        bookkeeping, not reusable concepts.
        """
        lines = []
        for prefix, mod in self.loaded_mods.items():
            dep_uri = getattr(mod, "__URI__", None)
            if not dep_uri:
                continue
            lines.append(f"  [prefix {prefix}, URI {dep_uri}]")
            entities = []
            for ent in self.all_entities():
                if getattr(ent, "base_uri", None) != dep_uri:
                    continue
                sk = ent.short_key
                # ``Ia...`` / ``Ra...`` are autogenerated scope-internal keys
                if len(sk) > 1 and sk[1].islower():
                    continue
                entities.append((sk, getattr(ent, "R1", "") or ""))
            entities.sort()
            for sk, lab in entities:
                lines.append(f'    - {sk} "{lab}"')
        return "\n".join(lines) if lines else "  (no dependencies loaded)"

    def search_entities(self, query: str, top_k: int = 10) -> list:
        """Cheap lexical scoring over label + description.

        For the pilot scale this is enough; the MCP design adds embeddings,
        but they only pay off at larger volume (see mcp_authoring.md sec. 5).
        """
        terms = [t for t in re.split(r"\W+", query.lower()) if len(t) > 1]
        hits = []
        for ent in self.all_entities():
            label = (getattr(ent, "R1", "") or "").lower()
            desc = (getattr(ent, "R2", "") or "").lower()
            if not (label or desc):
                continue
            score = sum(3 for t in terms if t in label) + sum(1 for t in terms if t in desc)
            if score <= 0:
                continue
            hits.append(
                EntityHit(
                    short_key=ent.short_key,
                    uri=ent.uri,
                    label=getattr(ent, "R1", "") or "",
                    description=(getattr(ent, "R2", "") or "")[:140],
                    score=score,
                )
            )
        hits.sort(key=lambda h: -h.score)
        return hits[:top_k]


# ---------------------------------------------------------------------------
# Module mutation + validation


_END_MOD_RE = re.compile(r"^p\.end_mod\(\s*\)\s*$", re.MULTILINE)


def append_to_module(path: Path, code_block: str) -> None:
    """Insert ``code_block`` immediately before the closing ``p.end_mod()``."""
    path = Path(path)
    txt = path.read_text()
    matches = list(_END_MOD_RE.finditer(txt))
    if not matches:
        raise RuntimeError(f"target module {path} has no `p.end_mod()` line")
    pos = matches[-1].start()
    code = code_block.rstrip()
    new_txt = txt[:pos].rstrip() + "\n\n\n" + code + "\n\n\n" + txt[pos:]
    path.write_text(new_txt)


def validate_module(path: Path) -> Tuple[bool, str]:
    """Round-trip: re-load the module via irkloader. ``reuse_loaded=False`` so
    the change is actually re-executed, not silently skipped."""
    try:
        irkloader.load_mod_from_path(str(path), prefix="_validate", reuse_loaded=False)
        return True, ""
    except Exception as exc:
        return False, f"{type(exc).__name__}: {exc}"


# ---------------------------------------------------------------------------
# Claude invocation + response parsing


def propose_via_claude(prompt: str, timeout: int = 600, model: str = "sonnet") -> ClaudeCallResult:
    """Invoke ``claude -p`` and return the response text plus usage metadata.

    Uses ``--output-format json`` so the CLI reports its API-equivalent cost
    per call (``total_cost_usd``) -- the basis for the ``cost_usd`` fields in
    bulk-run stats. Raises ``RuntimeError`` if the subprocess fails or the CLI
    reports an error result (e.g. a session limit)."""
    cmd = ["claude", "-p", prompt, "--output-format", "json", "--model", model]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        # On CLI-level errors stderr is often empty, but the json envelope (if
        # any) carries the human-readable reason, e.g. "You've hit your
        # session limit ... resets 2:10am".
        detail = _claude_error_detail(result.stdout) or result.stderr[:500]
        raise RuntimeError(f"`claude -p` exited {result.returncode}: {detail}")
    return _parse_claude_cli_json(result.stdout)


def _claude_error_detail(stdout: str) -> str:
    try:
        return str(json.loads(stdout).get("result", ""))[:500]
    except (json.JSONDecodeError, AttributeError):
        return ""


def _parse_claude_cli_json(stdout: str) -> ClaudeCallResult:
    """Parse the ``--output-format json`` envelope of ``claude -p``."""
    try:
        payload = json.loads(stdout)
    except json.JSONDecodeError:
        # Defensive: treat unparseable output as bare response text so a CLI
        # that ignores --output-format degrades to cost-less operation.
        return ClaudeCallResult(text=stdout)
    if payload.get("is_error"):
        raise RuntimeError(f"`claude -p` reported an error result: {str(payload.get('result'))[:500]}")
    dur_ms = payload.get("duration_api_ms")
    return ClaudeCallResult(
        text=payload.get("result") or "",
        cost_usd=payload.get("total_cost_usd"),
        duration_api_s=round(dur_ms / 1000, 1) if dur_ms else None,
        session_id=payload.get("session_id") or "",
        num_turns=payload.get("num_turns"),
    )


_CODE_BLOCK_RE = re.compile(r"```(?:python)?\s*\n(.*?)```", re.DOTALL)
_FORK_LINE_RE = re.compile(r"^\s*\(([a-z])\)\s*(.+?)\s*$", re.MULTILINE)


def parse_response(text: str) -> ProposalResult:
    """Parse a structured Claude response.

    The prompt instructs Claude to respond with one of:

    * ``OK:`` followed by a fenced python code block.
    * ``FORK:`` followed by ``Q: <question>`` and labelled options
      ``  (a) ...`` / ``  (b) ...`` / ``  (c) ...``.

    Anything else is reported as ``ERROR`` so the caller can re-prompt.
    """
    stripped = text.lstrip()
    if stripped.upper().startswith("FORK"):
        q_match = re.search(r"^\s*Q:\s*(.+?)\s*$", text, re.MULTILINE)
        options = _FORK_LINE_RE.findall(text)
        if q_match and options:
            return ProposalResult(
                kind="FORK",
                question=q_match.group(1),
                options=options,
                raw=text,
            )
        return ProposalResult(kind="ERROR", raw=text)

    code_match = _CODE_BLOCK_RE.search(text)
    if code_match:
        return ProposalResult(kind="OK", code=code_match.group(1).strip(), raw=text)
    return ProposalResult(kind="ERROR", raw=text)


# ---------------------------------------------------------------------------
# Prompt template


PROMPT_HEADER = """You are mapping the *statement* of a formal theorem into a pyirk content
module. Proofs are explicitly out of scope -- pyirk represents statements
only. Reuse existing entities aggressively; only introduce a new local
item if no entity in the listings below matches the needed concept.

CRITICAL: your output is *appended* to a working module that is already
fully bootstrapped. The module already executes ``import pyirk as p``,
loads its dependencies (e.g. ``ma = p.irkloader.load_mod_from_path(...,
prefix="ma")``), and has called ``p.start_mod(__URI__)``. Do NOT include
``import pyirk``, ``load_mod_from_path``, ``KeyManager``, ``register_mod``,
``start_mod``, or ``end_mod`` in your code block. Produce ONLY the new
``create_item`` / ``create_relation`` / ``with ...scope(...) as st:`` blocks.

Canonical example: an iff theorem (Pythagorean theorem, sides form) in pyirk.
Treat this as the structure you must follow.

```python
# Local value type so operator and named constant share a meaningful type.
I999 = p.create_item(
    R1__has_label="angle (quantity)",
    R2__has_description="real-number-valued angle magnitude (radians)",
    R3__is_subclass_of=p.I35["real number"],
)
# Local operator (no match in deps).
I1000 = p.create_item(
    R1__has_label="angle",
    R2__has_description="binary operator: angle between two polygon sides",
    R4__is_instance_of=p.I8["mathematical operation with arity 2"],
    R8__has_domain_of_argument_1=ma.I8172["polygon side"],
    R9__has_domain_of_argument_2=ma.I8172["polygon side"],
    R11__has_range_of_result=I999["angle (quantity)"],
)
# Local named constant.
I1001 = p.create_item(
    R1__has_label="right angle",
    R2__has_description="constant: pi/2",
    R4__is_instance_of=I999["angle (quantity)"],
)
# The theorem (iff -> I17 equivalence proposition).
I5000 = p.create_item(
    R1__has_label="Pythagorean theorem (sides form)",
    R4__is_instance_of=p.I17["equivalence proposition"],
)
with I5000["Pythagorean theorem (sides form)"].scope("setting") as st:
    st.new_var(ta=p.uq_instance_of(ma.I2917["planar triangle"]))
    st.new_var(sides=ma.I9148["get polygon sides ordered by length"](st.ta))
    a, b, c = p.unpack_tuple_item(st.sides)
    la = a.ma__R2495__has_length
    lb = b.ma__R2495__has_length
    lc = c.ma__R2495__has_length
with I5000["Pythagorean theorem (sides form)"].scope("premise") as st:
    st.new_equation(lhs=I1000["angle"](a, b), rhs=I1001["right angle"])
with I5000["Pythagorean theorem (sides form)"].scope("assertion") as st:
    st.new_equation(lhs=la**2 + lb**2, rhs=lc**2)
```

Key idioms to copy from that example:
* Short keys MUST match ``IXXXX`` / ``RXXXX`` where XXXX is digits
  (e.g. ``I5000``, ``R2495``). Do NOT use descriptive Python names like
  ``I_distance_quantity``; the key resolver will reject them.
* ``R3__is_subclass_of`` is the class-of-class relation.
  ``R4__is_instance_of`` is the member-of-class relation. Do not confuse.
* Theorem statements use three scopes: ``setting`` (universally quantified
  variables and derived expressions), ``premise`` (assumed equation),
  ``assertion`` (concluded equation). For I17 (iff), premise/assertion
  are interchangeable in meaning but the syntactic split is still required.
* Inside a scope, use ``st.new_var(...)`` and ``st.new_equation(lhs=..., rhs=...)``.
  Do NOT call ``p.new_equation`` at module top-level.
* If the source theorem talks about three points / a vertex / a triangle in
  plane geometry, prefer reusing ``ma.I2917 planar triangle`` plus
  ``ma.I9148 get polygon sides ordered by length`` over inventing point and
  distance items from scratch.
"""


PROMPT_RULES = """Modeling rules (strict):
* The encoding must follow the *source* type signature. When the source
  theorem declares typed variables (e.g. ``(x y : V)`` in Lean with
  ``V`` constrained to be a vector space), declare them in the ``setting``
  scope as ``p.uq_instance_of(<entity matching V>)``. If a matching entity
  exists in the dependency index (e.g. ``ma.I7151["vector"]`` for a
  ``V : Vector``-style declaration), reuse it. Do NOT re-encode the source
  variables under a derived geometric structure (e.g. a triangle) just
  because the worked example below happens to use one.
* Use ``p.I17["equivalence proposition"]`` for a biconditional / iff ("↔", "<->").
* Use ``p.I15["implication proposition"]`` for a one-directional implication.
* Each source theorem maps to its OWN distinct ``create_item(...)`` with
  its own ``R1__has_label``, even when structurally similar to one already
  in the working module. Reuse applies to *concept entities* (operators,
  value types, constants) but NOT to *theorem identities*: a Lean iff
  theorem and its companion implication theorem are two distinct pyirk
  items (one I17, one I15). Do NOT re-open ``with <existing-theorem>.scope
  (...)`` to encode a second source theorem.
* Each new theorem item MUST carry a source-reference attribute using the
  working-module relation ``R9999["has source reference"]``. Set it as a
  kwarg on ``create_item``:
  ``R9999__has_source_reference="<source identifier>"``, where the
  identifier is the content of the ``Source:`` line at the top of this
  prompt copied verbatim (single line, including any ``(URL)`` suffix).
  This applies to every source theorem, including implication forms that
  are companions of an iff theorem.
* ``R9999`` is already declared in the working module bootstrap. Do NOT
  re-declare it (no ``R9999 = p.create_relation(...)`` in your code
  block); just reference it as a kwarg on theorem items.
* For cross-module relations use the prefix attribute form, e.g.
  ``a.ma__R2495__has_length`` (NOT ``a.R2495__has_length``).
* pyirk Items overload ``**``, ``+``, ``*``; write equations directly on
  items (e.g. ``la**2 + lb**2``). Do NOT use ``items_to_symbols``.
* Builtin arity items: ``p.I7["mathematical operation with arity 1"]``,
  ``p.I8["mathematical operation with arity 2"]``, ``p.I9["mathematical
  operation with arity 3"]``. The label MUST match the key, and the
  arity MUST match the operator's actual number of arguments. Common
  failure mode: writing ``p.I8["mathematical operation with arity 1"]``
  for a unary operator -- use ``p.I7`` for unary instead.
* The signature is ``new_equation(lhs=..., rhs=...)`` -- two args, not three.
* When you introduce a new local *value* type (e.g. "angle (quantity)"),
  make it ``R3__is_subclass_of`` the most specific applicable parent so
  the operator result and any named constants share a meaningful type.

FORK is MANDATORY (not optional) when introducing a new item whose
mapping has more than one plausible encoding. You MUST emit FORK,
not OK, in any of these cases:

* The source concept (e.g. ``arccos``, ``inner product``, a specific
  algebraic operator) could be modeled either as a stand-alone item OR
  as a member of a small family with siblings sharing a parent type
  ("inverse trigonometric function", "binary form on a vector space",
  ...). The choice between these is a fork.
* A needed entity could plausibly REUSE an existing one from the
  dependency index OR be a new local item with narrower / broader
  scope. The choice is a fork.
* The new item's parent class is not uniquely determined by the source
  (e.g. ``p.I7["mathematical operation with arity 1"]`` vs
  ``ma.I1060["general function"]`` vs a new local type). The choice is
  a fork.

Do NOT confidently pick one encoding and ship OK if any of the above
applies. The point of FORK is to surface modeling choices to a human;
fluent confidence in the OK path defeats it. When in doubt, FORK.

Output format (exactly one of these two; nothing else, no prose around):

OK:
```python
<one block of pyirk code to be appended to the working module>
```

FORK:
Q: <one short question describing the modeling fork>
  (a) <option a, including the entity reuse / creation choice>
  (b) <option b>
  (c) <option c, often "reuse existing entity X">
"""


def build_import_prompt(
    *,
    theorem_text: str,
    source_info: str,
    retrieval_hits: list,
    dependency_index: str,
    working_summary: str,
    working_module_uri: str,
    loaded_prefixes: list,
    extra_context: str = "",
) -> str:
    hits_block = (
        "\n".join(f'  - {h.short_key} "{h.label}" -- {h.description}' for h in retrieval_hits)
        or "  (no hits)"
    )
    prefix_block = ", ".join(loaded_prefixes) or "(only builtins)"
    re_prompt_block = (
        f"\nRE-PROMPT CONTEXT (apply this when producing the next response):\n{extra_context}\n"
        if extra_context
        else ""
    )
    return (
        PROMPT_HEADER
        + f"\nSource: {source_info}\n"
        + f"\nWorking module URI: {working_module_uri}\n"
        + f"Already-loaded dependency prefixes: {prefix_block}\n"
        + re_prompt_block
        + f"\nTheorem statement (verbatim):\n{theorem_text}\n"
        + f"\nRetrieval hits (top-scored {len(retrieval_hits)} candidates by lexical match):\n{hits_block}\n"
        + f"\nFull entity index of loaded dependencies (label-only, in case retrieval missed something):\n{dependency_index}\n"
        + f"\nExisting items in the working module:\n{working_summary or '  (empty)'}\n"
        + "\n"
        + PROMPT_RULES
    )


# ---------------------------------------------------------------------------
# Utilities


_ITEM_DECL_RE = re.compile(
    r"^(I\d+)\s*=\s*p\.create_item\(\s*\n\s*R1__has_label=[\"']([^\"']+)[\"']",
    re.MULTILINE,
)


def summarize_module(path: Path, max_items: int = 50) -> str:
    """Brief listing of existing top-level ``IXXXX = create_item(...)`` items."""
    txt = Path(path).read_text()
    items = _ITEM_DECL_RE.findall(txt)
    return "\n".join(f'  - {key} "{label}"' for key, label in items[:max_items])


_URI_RE = re.compile(r"__URI__\s*=\s*[\"\']([^\"\']+)[\"\']")


def extract_module_uri(path: Path) -> str:
    m = _URI_RE.search(Path(path).read_text())
    if not m:
        raise RuntimeError(f"module {path} has no __URI__")
    return m.group(1)


# ---------------------------------------------------------------------------
# Key-collision remapping


_DECL_ITEM_SIMPLE_RE = re.compile(r"^(I\d+)\s*=\s*p\.create_item\(", re.MULTILINE)
_DECL_REL_SIMPLE_RE = re.compile(r"^(R\d+)\s*=\s*p\.create_relation\(", re.MULTILINE)
_DECL_ANY_KEY_RE = re.compile(r"^([IR]\d+)\s*=", re.MULTILINE)


def _collect_occupied_keys(working_module_path: Path) -> set:
    """Return all known short keys: core.ds (builtins + loaded deps) + declarations in working module."""
    occupied = set()
    for ent in core.ds.items.values():
        occupied.add(ent.short_key)
    for ent in core.ds.relations.values():
        occupied.add(ent.short_key)
    txt = Path(working_module_path).read_text()
    for m in _DECL_ANY_KEY_RE.finditer(txt):
        occupied.add(m.group(1))
    return occupied


def remap_colliding_keys(code: str, occupied) -> tuple:
    """Remap declared keys in *code* that collide with *occupied*.

    Returns ``(new_code, mapping)`` where *mapping* is ``old_key -> new_key``.
    When nothing collides the returned code is byte-identical to the input and
    *mapping* is an empty dict.

    Replacement is deterministic: the numeric part is incremented from the
    original value until a key is free in ``occupied ∪ all_declared ∪ chosen``.

    Only top-level ``IXXXX = p.create_item(`` and ``RXXXX = p.create_relation(``
    declarations are considered.  For each remapped key all occurrences are
    updated: the assignment target, the label-reference form ``KEY["..."]``, and
    (for declared relations) the kwarg form ``KEY__attr_name=``.  Prefixed
    cross-module references (``ma__RXXXX``, ``a.ma__RXXXX``) are left untouched
    because the key is preceded by a word character or dot, which the negative
    lookbehind ``(?<![.\\w])`` rejects.
    """
    occupied = set(occupied)
    declared_items = [m.group(1) for m in _DECL_ITEM_SIMPLE_RE.finditer(code)]
    declared_rels = [m.group(1) for m in _DECL_REL_SIMPLE_RE.finditer(code)]
    declared_rels_set = set(declared_rels)
    all_declared = set(declared_items) | declared_rels_set

    # prevent replacements from colliding with other block-declared keys
    full_occupied = occupied | all_declared

    mapping: dict = {}
    chosen: set = set()  # replacement keys already picked in this pass

    for key in declared_items + declared_rels:
        if key not in occupied:
            continue
        prefix = key[0]
        num = int(key[1:]) + 1
        while True:
            candidate = f"{prefix}{num}"
            if candidate not in full_occupied and candidate not in chosen:
                mapping[key] = candidate
                chosen.add(candidate)
                break
            num += 1

    if not mapping:
        return code, {}

    new_code = code
    for old_key, new_key in mapping.items():
        pat = re.escape(old_key)
        # 1. assignment target: KEY at start of line followed by =
        new_code = re.sub(r"(?m)^" + pat + r"(?=\s*=)", new_key, new_code)
        # 2. label-reference form: KEY["..."] not preceded by . or \w
        new_code = re.sub(r"(?<![.\w])" + pat + r"(?=\[)", new_key, new_code)
        # 3. kwarg form of a declared relation: KEY__attr_name= not preceded by . or \w
        if old_key in declared_rels_set:
            new_code = re.sub(r"(?<![.\w])" + pat + r"(?=__)", new_key, new_code)

    return new_code, mapping


# ---------------------------------------------------------------------------
# Guards for the non-collision failure classes (see bulk_runs2/SUMMARY.md)

# String literals (incl. triple-quoted, optional prefix) and comments. Their
# contents may legitimately hold non-ASCII (math labels/descriptions), so they
# are masked out before scanning the *code* for stray Lean operators.
_STRING_OR_COMMENT_RE = re.compile(
    r"""[rbfuRBFU]{0,3}(?:\"\"\".*?\"\"\"|'''.*?'''|"(?:\\.|[^"\\\n])*"|'(?:\\.|[^'\\\n])*')""" r"|#[^\n]*",
    re.DOTALL,
)


def _mask_strings_and_comments(code: str) -> str:
    """Blank out string-literal and comment spans (keeping newlines) so the
    remaining text has valid line/column coordinates for the real code only."""
    return _STRING_OR_COMMENT_RE.sub(lambda m: "".join(c if c == "\n" else " " for c in m.group(0)), code)


def find_nonascii_outside_strings(code: str) -> list:
    """Return ``[(lineno, col, char), ...]`` for non-ASCII characters in actual
    code (outside string literals and comments).

    Such characters are almost always Lean operators (``→``, ``∘``, ``•``,
    ``≤`` …) transcribed verbatim into the Python block; they raise a cryptic
    ``SyntaxError`` only at module re-load. Detecting them up front lets the
    pipeline re-prompt with a precise message instead.
    """
    masked = _mask_strings_and_comments(code)
    hits = []
    for lineno, line in enumerate(masked.splitlines(), start=1):
        for col, ch in enumerate(line, start=1):
            if ord(ch) > 127:
                hits.append((lineno, col, ch))
    return hits


_SCOPE_OPEN_RE = re.compile(r"^\s*with\s+([IR]\d+)\s*\[", re.MULTILINE)


def find_reopened_scopes(code: str) -> list:
    """Return the distinct keys that *code* opens a ``.scope(...)`` on without
    declaring them in the same block.

    Opening ``with KEY[...].scope(...)`` on a KEY not created by a
    ``create_item`` / ``create_relation`` in this very block re-uses a theorem
    item from an earlier statement, which raises ``InvalidScopeNameError`` (the
    item already owns its scopes). Every theorem must own a fresh item.
    """
    declared = {m.group(1) for m in _DECL_ITEM_SIMPLE_RE.finditer(code)}
    declared |= {m.group(1) for m in _DECL_REL_SIMPLE_RE.finditer(code)}
    reopened, seen = [], set()
    for m in _SCOPE_OPEN_RE.finditer(code):
        key = m.group(1)
        if key not in declared and key not in seen:
            seen.add(key)
            reopened.append(key)
    return reopened


# ---------------------------------------------------------------------------
# Generic import loop (shared by all source adapters)


def import_one_statement(
    *,
    session: Session,
    theorem_text: str,
    source_info: str,
    working_module_path: Path,
    ask_user: Callable[[str, list], str],
    extra_query_text: str = "",
    max_attempts: int = 3,
    claude_timeout: int = 600,
    on_progress: Optional[Callable[[str], None]] = None,
    events: Optional[list] = None,
) -> Tuple[bool, str]:
    """Drive one statement through retrieval → propose → escalate → validate.

    Returns ``(ok, message)``. If ``events`` is a list, structured per-attempt
    records (dicts) are appended to it -- the basis for bulk-run metrics
    (FORK rate, validation-retry rate etc.).
    """
    log = on_progress or (lambda msg: None)
    if events is None:
        events = []  # discard silently; keeps the append sites unconditional

    query = " ".join(filter(None, [theorem_text, extra_query_text, source_info]))
    hits = session.search_entities(query, top_k=15)
    log(f"retrieval: {len(hits)} hits")

    working_summary = summarize_module(working_module_path)
    working_uri = extract_module_uri(working_module_path)
    dependency_index = session.dependency_label_index()

    extra_context = ""
    for attempt in range(1, max_attempts + 1):
        prompt = build_import_prompt(
            theorem_text=theorem_text,
            source_info=source_info,
            retrieval_hits=hits,
            dependency_index=dependency_index,
            working_summary=working_summary,
            working_module_uri=working_uri,
            loaded_prefixes=list(session.loaded_mods.keys()),
            extra_context=extra_context,
        )
        log(f"attempt {attempt}: calling claude")
        try:
            raw = propose_via_claude(prompt, timeout=claude_timeout)
        except subprocess.TimeoutExpired:
            # A timeout used to propagate out and kill the whole theorem as a
            # fatal "error" with no retry. Treat it as a retryable attempt
            # instead. (Note: with the default 600 s, up to max_attempts
            # timeouts can exceed an outer worker timeout -- that is fine, the
            # idempotent --resume picks the theorem up again next run.)
            events.append({"event": "timeout", "attempt": attempt, "timeout_s": claude_timeout})
            log(f"claude call timed out after {claude_timeout}s")
            extra_context = (
                f"Your previous attempt did not return within {claude_timeout} "
                "seconds and was aborted. Produce the MINIMAL correct encoding: "
                "no prose, keep the code block as small as the theorem allows."
            )
            continue
        if isinstance(raw, str):
            # test mocks and other stand-ins may return bare response text
            raw = ClaudeCallResult(text=raw)
        # per-call usage, attached to whichever event this attempt produces
        usage = {"cost_usd": raw.cost_usd} if raw.cost_usd is not None else {}
        result = parse_response(raw.text)

        if result.kind == "FORK":
            log(f"FORK: {result.question}")
            try:
                choice = ask_user(result.question, result.options)
            except ForkPending:
                # still account for the claude call that surfaced the fork
                events.append(
                    {"event": "fork_pending", "attempt": attempt, "question": result.question, **usage}
                )
                raise
            events.append(
                {
                    "event": "fork",
                    "attempt": attempt,
                    "question": result.question,
                    "options": list(result.options),
                    "choice": choice,
                    **usage,
                }
            )
            extra_context = (
                f"User resolved a previous modeling fork.\n"
                f"Question: {result.question}\n"
                f"Chosen option: ({choice})\n"
                f"Now produce the OK response."
            )
            continue

        if result.kind != "OK":
            events.append({"event": "malformed", "attempt": attempt, **usage})
            extra_context = (
                "Previous response was malformed -- it did not match either the "
                "OK or FORK output format. Try again, strictly following the "
                "output format. Raw previous response (excerpt):\n"
                f"{result.raw[:400]}"
            )
            continue

        # OK: remap colliding keys, then guard against the known non-collision
        # failure classes before the (expensive) round-trip validation.
        occupied = _collect_occupied_keys(working_module_path)
        code_to_append, remap = remap_colliding_keys(result.code, occupied)
        if remap:
            events.append({"event": "key_remap", "attempt": attempt, "mapping": remap})

        nonascii = find_nonascii_outside_strings(code_to_append)
        if nonascii:
            sample = ", ".join(f"{ch!r} (line {ln}, col {col})" for ln, col, ch in nonascii[:6])
            events.append(
                {"event": "nonascii", "attempt": attempt, "chars": [h[2] for h in nonascii], **usage}
            )
            log(f"non-ASCII in code: {sample}")
            extra_context = (
                "Your code block contains non-ASCII character(s) OUTSIDE string "
                f"literals: {sample}. These are Lean operators transcribed verbatim "
                "and are illegal in Python source. Rewrite using pyirk constructs: "
                "ASCII arithmetic on items (** + * for the overloaded operators), "
                "the appropriate operator/relation items for composition, ordering, "
                "membership etc., and never put symbols like the function arrow, "
                "ring/scalar dot, composition ring, <=, or set membership into the "
                "code. Non-ASCII is fine ONLY inside string labels/descriptions."
            )
            continue

        reopened = find_reopened_scopes(code_to_append)
        if reopened:
            keys = ", ".join(reopened)
            events.append({"event": "scope_reopen", "attempt": attempt, "keys": reopened, **usage})
            log(f"scope reopen on non-declared item(s): {keys}")
            extra_context = (
                f"Your code opens a scope (`with ...scope(...)`) on item(s) {keys} "
                "that are NOT created in this block. That re-uses a theorem item "
                "from an earlier statement and fails (the item already owns its "
                "scopes). Every theorem needs its OWN new `create_item(...)`; open "
                "scopes only on the freshly created theorem item of THIS statement."
            )
            continue

        backup = working_module_path.read_text()
        try:
            append_to_module(working_module_path, code_to_append)
        except Exception as exc:
            working_module_path.write_text(backup)
            events.append({"event": "append_fail", "attempt": attempt, "error": str(exc)[:300], **usage})
            extra_context = f"append_to_module failed: {exc}. Try again."
            continue

        ok, err = validate_module(working_module_path)
        if ok:
            log("validation OK")
            events.append({"event": "ok", "attempt": attempt, **usage})
            return True, "ok"
        # rollback + re-prompt with the validation error
        working_module_path.write_text(backup)
        events.append({"event": "validation_fail", "attempt": attempt, "error": err[:300], **usage})
        extra_context = (
            "Previous attempt was syntactically appended but failed "
            f"validation:\n{err[:600]}\n"
            "Diagnose the error and produce a corrected OK response."
        )
        log(f"validation FAIL: {err[:120]}")

    events.append({"event": "gave_up", "attempts": max_attempts})
    return False, f"gave up after {max_attempts} attempts"


_BOOTSTRAP_TEMPLATE = '''\
"""Auto-generated pyirk content module for theorem import."""

import pyirk as p

ma = p.irkloader.load_mod_from_path({ocse_path!r}, prefix="ma")

__URI__ = "{uri}"
keymanager = p.KeyManager()
p.register_mod(__URI__, keymanager)
p.start_mod(__URI__)


R9999 = p.create_relation(
    R1__has_label="has source reference",
    R2__has_description="verbatim source identifier of an imported statement",
)


p.end_mod()
'''


def bootstrap_working_module(path, uri: str, ocse_path: str) -> Path:
    """Create a fresh pyirk content module at ``path`` with the standard bootstrap.

    The bootstrap declares ``R9999["has source reference"]`` so the prompt rules
    can reference it (see ``PROMPT_RULES``). Subsequent theorem appends use
    :func:`append_to_module`, which inserts before the closing ``p.end_mod()``.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    txt = _BOOTSTRAP_TEMPLATE.format(uri=uri, ocse_path=str(ocse_path))
    path.write_text(txt)
    return path


def ask_user_via_stdin(question: str, options: list) -> str:
    """Default interactive escalation -- prompt on stdin/stdout."""
    print()
    print(question)
    for letter, desc in options:
        print(f"  ({letter}) {desc}")
    while True:
        choice = input("Your choice: ").strip().lower()
        if any(choice == letter for letter, _ in options):
            return choice
        print(f"  please pick one of: {', '.join(letter for letter, _ in options)}")


def fork_policy_first(question: str, options: list) -> str:
    """Non-interactive FORK policy: always pick the first offered option.

    For unattended bulk runs. The arbitrary-but-documented choice keeps the
    import going; the question/options/choice are recorded in the per-theorem
    event log so the decision can be audited later.
    """
    if not options:
        raise ValueError(f"FORK question offered no options: {question!r}")
    return options[0][0]


def fork_policy_skip(question: str, options: list) -> str:
    """Non-interactive FORK policy: do not decide -- skip the statement.

    Raises :class:`ForkPending`; the caller records the theorem as pending
    instead of resolving the modeling ambiguity arbitrarily.
    """
    raise ForkPending(question, options)
