# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
    - main
    - develop
    - develop_carsten
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DEBUG_WITH_SSH: true

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: debug env
      run: |
        echo "$PYERK_TEST_DATA_PARENT_PATH"

    - name: Installing requirements
      run: |
        # install this package
        pwd
        pip install -r requirements.txt


    - name: install pyirk
      run: |
        # install in editable mode -> simplify the discovery of the (internal) test data
        pip install -e .

    - name: setup configuration file
      run: |
        pyirk --bootstrap-config --ci-mode

    # - name: run all tests
    #   run: |
    #     python -m unittest


    # debugging (set env.DEBUG_WITH_SSH to true (see above))
    - name: Setup tmate session
      if: env.DEBUG_WITH_SSH == 'true'
      id: tmate
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true

    # this exports the ad-hoc ssh-connection address to an text file such that it can be accessed via API
    # this allows to connect to the debugging ssh server without manual copy-pasting
    # see https://github.com/cknoll/github-ci-ssh-connect

    - name: Capture tmate output
      if: env.DEBUG_WITH_SSH == 'true'
      run: |
          echo $(cat /home/runner/work/_temp/_runner_file_commands/* | grep ::notice::SSH | awk '{print $NF}') > tmate-connection.txt

    - name: Upload tmate logs as artifact
      if: env.DEBUG_WITH_SSH == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: tmate-connection
        path: tmate-connection.txt
